[2025-02-04T18:34:45.234+0000] {processor.py:186} INFO - Started process (PID=31) to work on /opt/airflow/dags/app.py
[2025-02-04T18:34:45.237+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-04T18:34:45.244+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:34:45.244+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-04T18:34:45.493+0000] {processor.py:925} INFO - DAG(s) 'fetch_and_store_amazon_books' retrieved from /opt/airflow/dags/app.py
[2025-02-04T18:34:45.727+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:34:45.727+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-04T18:34:45.786+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.562 seconds
[2025-02-04T18:35:16.518+0000] {processor.py:186} INFO - Started process (PID=102) to work on /opt/airflow/dags/app.py
[2025-02-04T18:35:16.524+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-04T18:35:16.533+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:35:16.532+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-04T18:35:16.721+0000] {processor.py:925} INFO - DAG(s) 'fetch_and_store_amazon_books' retrieved from /opt/airflow/dags/app.py
[2025-02-04T18:35:16.757+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:35:16.757+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-04T18:35:16.843+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.347 seconds
[2025-02-04T18:35:47.002+0000] {processor.py:186} INFO - Started process (PID=166) to work on /opt/airflow/dags/app.py
[2025-02-04T18:35:47.006+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-04T18:35:47.010+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:35:47.009+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-04T18:35:47.110+0000] {processor.py:925} INFO - DAG(s) 'fetch_and_store_amazon_books' retrieved from /opt/airflow/dags/app.py
[2025-02-04T18:35:47.133+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:35:47.133+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-04T18:35:47.174+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.176 seconds
[2025-02-04T18:36:02.862+0000] {processor.py:186} INFO - Started process (PID=228) to work on /opt/airflow/dags/app.py
[2025-02-04T18:36:02.865+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-04T18:36:02.871+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:36:02.870+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-04T18:36:02.963+0000] {processor.py:925} INFO - DAG(s) 'fetch_and_store_amazon_books' retrieved from /opt/airflow/dags/app.py
[2025-02-04T18:36:02.998+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:36:02.997+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-04T18:36:03.047+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.191 seconds
[2025-02-04T18:36:06.938+0000] {processor.py:186} INFO - Started process (PID=229) to work on /opt/airflow/dags/app.py
[2025-02-04T18:36:06.942+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-04T18:36:06.948+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:36:06.947+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-04T18:36:07.105+0000] {processor.py:925} INFO - DAG(s) 'fetch_and_store_amazon_books' retrieved from /opt/airflow/dags/app.py
[2025-02-04T18:36:07.141+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:36:07.140+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-04T18:36:07.185+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.261 seconds
[2025-02-04T18:36:37.843+0000] {processor.py:186} INFO - Started process (PID=293) to work on /opt/airflow/dags/app.py
[2025-02-04T18:36:37.849+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-04T18:36:37.857+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:36:37.856+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-04T18:36:37.978+0000] {processor.py:925} INFO - DAG(s) 'fetch_and_store_amazon_books' retrieved from /opt/airflow/dags/app.py
[2025-02-04T18:36:38.013+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:36:38.012+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-04T18:36:38.048+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.224 seconds
[2025-02-04T18:36:52.796+0000] {processor.py:186} INFO - Started process (PID=301) to work on /opt/airflow/dags/app.py
[2025-02-04T18:36:52.799+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-04T18:36:52.805+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:36:52.804+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-04T18:36:52.940+0000] {processor.py:925} INFO - DAG(s) 'fetch_and_store_amazon_books' retrieved from /opt/airflow/dags/app.py
[2025-02-04T18:36:52.973+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:36:52.972+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-04T18:36:53.014+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.242 seconds
[2025-02-04T18:37:23.495+0000] {processor.py:186} INFO - Started process (PID=365) to work on /opt/airflow/dags/app.py
[2025-02-04T18:37:23.498+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-04T18:37:23.501+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:37:23.500+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-04T18:37:23.594+0000] {processor.py:925} INFO - DAG(s) 'fetch_and_store_amazon_books' retrieved from /opt/airflow/dags/app.py
[2025-02-04T18:37:23.613+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:37:23.613+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-04T18:37:23.638+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.149 seconds
[2025-02-04T18:37:53.820+0000] {processor.py:186} INFO - Started process (PID=429) to work on /opt/airflow/dags/app.py
[2025-02-04T18:37:53.823+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-04T18:37:53.826+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:37:53.825+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-04T18:37:53.916+0000] {processor.py:925} INFO - DAG(s) 'fetch_and_store_amazon_books' retrieved from /opt/airflow/dags/app.py
[2025-02-04T18:37:53.935+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:37:53.935+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-04T18:37:53.961+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.147 seconds
[2025-02-04T18:37:57.887+0000] {processor.py:186} INFO - Started process (PID=451) to work on /opt/airflow/dags/app.py
[2025-02-04T18:37:57.890+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-04T18:37:57.893+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:37:57.892+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-04T18:37:57.960+0000] {processor.py:925} INFO - DAG(s) 'fetch_and_store_amazon_books' retrieved from /opt/airflow/dags/app.py
[2025-02-04T18:37:57.976+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:37:57.976+0000] {taskinstance.py:3313} ERROR - {'DAG Id': 'fetch_and_store_amazon_books', 'Task Id': 'fetch_book_data', 'Run Id': 'scheduled__2024-06-27T00:00:00+00:00', 'Hostname': '01f8178c85f9', 'External Executor Id': 'ff0eba7d-da09-416c-a6a7-6b72cb143c5c'}
[2025-02-04T18:37:57.995+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-02-04T18:37:57.996+0000] {logging_mixin.py:190} INFO - Task start:2025-02-04 18:28:16.446962+00:00 end:2025-02-04 18:37:57.994566+00:00 duration:581.547604
[2025-02-04T18:37:57.998+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): fetch_book_data> dag:<DAG: fetch_and_store_amazon_books> dagrun:<DagRun fetch_and_store_amazon_books @ 2024-06-27 00:00:00+00:00: scheduled__2024-06-27T00:00:00+00:00, state:running, queued_at: 2025-02-04 18:27:09.903658+00:00. externally triggered: False>
[2025-02-04T18:37:58.000+0000] {logging_mixin.py:190} INFO - Failure caused by {'DAG Id': 'fetch_and_store_amazon_books', 'Task Id': 'fetch_book_data', 'Run Id': 'scheduled__2024-06-27T00:00:00+00:00', 'Hostname': '01f8178c85f9', 'External Executor Id': 'ff0eba7d-da09-416c-a6a7-6b72cb143c5c'}
[2025-02-04T18:37:58.001+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:37:58.001+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=fetch_and_store_amazon_books, task_id=fetch_book_data, run_id=scheduled__2024-06-27T00:00:00+00:00, execution_date=20240627T000000, start_date=20250204T182816, end_date=20250204T183757
[2025-02-04T18:37:58.016+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:37:58.016+0000] {processor.py:876} INFO - Executed callback for <TaskInstance: fetch_and_store_amazon_books.fetch_book_data scheduled__2024-06-27T00:00:00+00:00 [up_for_retry]> in state up_for_retry
[2025-02-04T18:37:58.020+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:37:58.020+0000] {taskinstance.py:3313} ERROR - {'DAG Id': 'fetch_and_store_amazon_books', 'Task Id': 'fetch_book_data', 'Run Id': 'scheduled__2024-06-28T00:00:00+00:00', 'Hostname': '01f8178c85f9', 'External Executor Id': '52a83c20-96ea-4733-8ab1-0b8e0bb12888'}
[2025-02-04T18:37:58.026+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-02-04T18:37:58.027+0000] {logging_mixin.py:190} INFO - Task start:2025-02-04 18:28:13.835863+00:00 end:2025-02-04 18:37:58.026237+00:00 duration:584.190374
[2025-02-04T18:37:58.028+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): fetch_book_data> dag:<DAG: fetch_and_store_amazon_books> dagrun:<DagRun fetch_and_store_amazon_books @ 2024-06-28 00:00:00+00:00: scheduled__2024-06-28T00:00:00+00:00, state:running, queued_at: 2025-02-04 18:27:10.024644+00:00. externally triggered: False>
[2025-02-04T18:37:58.029+0000] {logging_mixin.py:190} INFO - Failure caused by {'DAG Id': 'fetch_and_store_amazon_books', 'Task Id': 'fetch_book_data', 'Run Id': 'scheduled__2024-06-28T00:00:00+00:00', 'Hostname': '01f8178c85f9', 'External Executor Id': '52a83c20-96ea-4733-8ab1-0b8e0bb12888'}
[2025-02-04T18:37:58.030+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:37:58.030+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=fetch_and_store_amazon_books, task_id=fetch_book_data, run_id=scheduled__2024-06-28T00:00:00+00:00, execution_date=20240628T000000, start_date=20250204T182813, end_date=20250204T183758
[2025-02-04T18:37:58.034+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:37:58.034+0000] {processor.py:876} INFO - Executed callback for <TaskInstance: fetch_and_store_amazon_books.fetch_book_data scheduled__2024-06-28T00:00:00+00:00 [up_for_retry]> in state up_for_retry
[2025-02-04T18:37:58.041+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:37:58.041+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-04T18:37:58.060+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.179 seconds
[2025-02-04T18:38:08.012+0000] {processor.py:186} INFO - Started process (PID=487) to work on /opt/airflow/dags/app.py
[2025-02-04T18:38:08.015+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-04T18:38:08.020+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:38:08.019+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-04T18:38:08.125+0000] {processor.py:925} INFO - DAG(s) 'fetch_and_store_amazon_books' retrieved from /opt/airflow/dags/app.py
[2025-02-04T18:38:08.147+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:38:08.147+0000] {taskinstance.py:3313} ERROR - {'DAG Id': 'fetch_and_store_amazon_books', 'Task Id': 'fetch_book_data', 'Run Id': 'manual__2025-02-04T18:27:07.412959+00:00', 'Hostname': '01f8178c85f9', 'External Executor Id': '52d5d1a4-a034-414c-b7f4-fc7329512f8f'}
[2025-02-04T18:38:08.166+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-02-04T18:38:08.167+0000] {logging_mixin.py:190} INFO - Task start:2025-02-04 18:28:13.564147+00:00 end:2025-02-04 18:38:08.165787+00:00 duration:594.60164
[2025-02-04T18:38:08.169+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): fetch_book_data> dag:<DAG: fetch_and_store_amazon_books> dagrun:<DagRun fetch_and_store_amazon_books @ 2025-02-04 18:27:07.412959+00:00: manual__2025-02-04T18:27:07.412959+00:00, state:running, queued_at: 2025-02-04 18:27:07.449238+00:00. externally triggered: True>
[2025-02-04T18:38:08.170+0000] {logging_mixin.py:190} INFO - Failure caused by {'DAG Id': 'fetch_and_store_amazon_books', 'Task Id': 'fetch_book_data', 'Run Id': 'manual__2025-02-04T18:27:07.412959+00:00', 'Hostname': '01f8178c85f9', 'External Executor Id': '52d5d1a4-a034-414c-b7f4-fc7329512f8f'}
[2025-02-04T18:38:08.171+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:38:08.171+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=fetch_and_store_amazon_books, task_id=fetch_book_data, run_id=manual__2025-02-04T18:27:07.412959+00:00, execution_date=20250204T182707, start_date=20250204T182813, end_date=20250204T183808
[2025-02-04T18:38:08.187+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:38:08.187+0000] {processor.py:876} INFO - Executed callback for <TaskInstance: fetch_and_store_amazon_books.fetch_book_data manual__2025-02-04T18:27:07.412959+00:00 [up_for_retry]> in state up_for_retry
[2025-02-04T18:38:08.191+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:38:08.191+0000] {taskinstance.py:3313} ERROR - {'DAG Id': 'fetch_and_store_amazon_books', 'Task Id': 'fetch_book_data', 'Run Id': 'scheduled__2024-06-26T00:00:00+00:00', 'Hostname': '01f8178c85f9', 'External Executor Id': '308a60b7-289a-4df0-9031-bf5c882f5550'}
[2025-02-04T18:38:08.198+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-02-04T18:38:08.200+0000] {logging_mixin.py:190} INFO - Task start:2025-02-04 18:28:07.081438+00:00 end:2025-02-04 18:38:08.198406+00:00 duration:601.116968
[2025-02-04T18:38:08.201+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): fetch_book_data> dag:<DAG: fetch_and_store_amazon_books> dagrun:<DagRun fetch_and_store_amazon_books @ 2024-06-26 00:00:00+00:00: scheduled__2024-06-26T00:00:00+00:00, state:running, queued_at: 2025-02-04 18:27:09.773934+00:00. externally triggered: False>
[2025-02-04T18:38:08.202+0000] {logging_mixin.py:190} INFO - Failure caused by {'DAG Id': 'fetch_and_store_amazon_books', 'Task Id': 'fetch_book_data', 'Run Id': 'scheduled__2024-06-26T00:00:00+00:00', 'Hostname': '01f8178c85f9', 'External Executor Id': '308a60b7-289a-4df0-9031-bf5c882f5550'}
[2025-02-04T18:38:08.203+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:38:08.203+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=fetch_and_store_amazon_books, task_id=fetch_book_data, run_id=scheduled__2024-06-26T00:00:00+00:00, execution_date=20240626T000000, start_date=20250204T182807, end_date=20250204T183808
[2025-02-04T18:38:08.209+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:38:08.209+0000] {processor.py:876} INFO - Executed callback for <TaskInstance: fetch_and_store_amazon_books.fetch_book_data scheduled__2024-06-26T00:00:00+00:00 [up_for_retry]> in state up_for_retry
[2025-02-04T18:38:08.212+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:38:08.212+0000] {taskinstance.py:3313} ERROR - {'DAG Id': 'fetch_and_store_amazon_books', 'Task Id': 'fetch_book_data', 'Run Id': 'scheduled__2024-07-02T00:00:00+00:00', 'Hostname': '01f8178c85f9', 'External Executor Id': '901839be-5bb8-4950-b6ba-0a058ed7bd8d'}
[2025-02-04T18:38:08.217+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-02-04T18:38:08.219+0000] {logging_mixin.py:190} INFO - Task start:2025-02-04 18:28:05.029206+00:00 end:2025-02-04 18:38:08.217820+00:00 duration:603.188614
[2025-02-04T18:38:08.220+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): fetch_book_data> dag:<DAG: fetch_and_store_amazon_books> dagrun:<DagRun fetch_and_store_amazon_books @ 2024-07-02 00:00:00+00:00: scheduled__2024-07-02T00:00:00+00:00, state:running, queued_at: 2025-02-04 18:27:10.735300+00:00. externally triggered: False>
[2025-02-04T18:38:08.222+0000] {logging_mixin.py:190} INFO - Failure caused by {'DAG Id': 'fetch_and_store_amazon_books', 'Task Id': 'fetch_book_data', 'Run Id': 'scheduled__2024-07-02T00:00:00+00:00', 'Hostname': '01f8178c85f9', 'External Executor Id': '901839be-5bb8-4950-b6ba-0a058ed7bd8d'}
[2025-02-04T18:38:08.224+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:38:08.224+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=fetch_and_store_amazon_books, task_id=fetch_book_data, run_id=scheduled__2024-07-02T00:00:00+00:00, execution_date=20240702T000000, start_date=20250204T182805, end_date=20250204T183808
[2025-02-04T18:38:08.228+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:38:08.228+0000] {processor.py:876} INFO - Executed callback for <TaskInstance: fetch_and_store_amazon_books.fetch_book_data scheduled__2024-07-02T00:00:00+00:00 [up_for_retry]> in state up_for_retry
[2025-02-04T18:38:08.231+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:38:08.231+0000] {taskinstance.py:3313} ERROR - {'DAG Id': 'fetch_and_store_amazon_books', 'Task Id': 'fetch_book_data', 'Run Id': 'scheduled__2024-07-04T00:00:00+00:00', 'Hostname': '01f8178c85f9', 'External Executor Id': 'bbc9bccc-8601-4dad-a03b-272c57e92bee'}
[2025-02-04T18:38:08.235+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-02-04T18:38:08.236+0000] {logging_mixin.py:190} INFO - Task start:2025-02-04 18:28:17.306445+00:00 end:2025-02-04 18:38:08.235544+00:00 duration:590.929099
[2025-02-04T18:38:08.237+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): fetch_book_data> dag:<DAG: fetch_and_store_amazon_books> dagrun:<DagRun fetch_and_store_amazon_books @ 2024-07-04 00:00:00+00:00: scheduled__2024-07-04T00:00:00+00:00, state:running, queued_at: 2025-02-04 18:27:11.191934+00:00. externally triggered: False>
[2025-02-04T18:38:08.238+0000] {logging_mixin.py:190} INFO - Failure caused by {'DAG Id': 'fetch_and_store_amazon_books', 'Task Id': 'fetch_book_data', 'Run Id': 'scheduled__2024-07-04T00:00:00+00:00', 'Hostname': '01f8178c85f9', 'External Executor Id': 'bbc9bccc-8601-4dad-a03b-272c57e92bee'}
[2025-02-04T18:38:08.240+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:38:08.240+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=fetch_and_store_amazon_books, task_id=fetch_book_data, run_id=scheduled__2024-07-04T00:00:00+00:00, execution_date=20240704T000000, start_date=20250204T182817, end_date=20250204T183808
[2025-02-04T18:38:08.243+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:38:08.243+0000] {processor.py:876} INFO - Executed callback for <TaskInstance: fetch_and_store_amazon_books.fetch_book_data scheduled__2024-07-04T00:00:00+00:00 [up_for_retry]> in state up_for_retry
[2025-02-04T18:38:08.246+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:38:08.245+0000] {taskinstance.py:3313} ERROR - {'DAG Id': 'fetch_and_store_amazon_books', 'Task Id': 'fetch_book_data', 'Run Id': 'scheduled__2024-06-21T00:00:00+00:00', 'Hostname': '01f8178c85f9', 'External Executor Id': '722fea71-8334-43c8-a84a-af1324084809'}
[2025-02-04T18:38:08.250+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-02-04T18:38:08.250+0000] {logging_mixin.py:190} INFO - Task start:2025-02-04 18:27:59.981237+00:00 end:2025-02-04 18:38:08.249919+00:00 duration:608.268682
[2025-02-04T18:38:08.251+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): fetch_book_data> dag:<DAG: fetch_and_store_amazon_books> dagrun:<DagRun fetch_and_store_amazon_books @ 2024-06-21 00:00:00+00:00: scheduled__2024-06-21T00:00:00+00:00, state:running, queued_at: 2025-02-04 18:27:09.109872+00:00. externally triggered: False>
[2025-02-04T18:38:08.252+0000] {logging_mixin.py:190} INFO - Failure caused by {'DAG Id': 'fetch_and_store_amazon_books', 'Task Id': 'fetch_book_data', 'Run Id': 'scheduled__2024-06-21T00:00:00+00:00', 'Hostname': '01f8178c85f9', 'External Executor Id': '722fea71-8334-43c8-a84a-af1324084809'}
[2025-02-04T18:38:08.255+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:38:08.255+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=fetch_and_store_amazon_books, task_id=fetch_book_data, run_id=scheduled__2024-06-21T00:00:00+00:00, execution_date=20240621T000000, start_date=20250204T182759, end_date=20250204T183808
[2025-02-04T18:38:08.258+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:38:08.258+0000] {processor.py:876} INFO - Executed callback for <TaskInstance: fetch_and_store_amazon_books.fetch_book_data scheduled__2024-06-21T00:00:00+00:00 [up_for_retry]> in state up_for_retry
[2025-02-04T18:38:08.260+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:38:08.260+0000] {taskinstance.py:3313} ERROR - {'DAG Id': 'fetch_and_store_amazon_books', 'Task Id': 'fetch_book_data', 'Run Id': 'scheduled__2024-06-23T00:00:00+00:00', 'Hostname': '01f8178c85f9', 'External Executor Id': 'f9861682-0bff-41e8-80af-ed6b910c53a2'}
[2025-02-04T18:38:08.264+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-02-04T18:38:08.265+0000] {logging_mixin.py:190} INFO - Task start:2025-02-04 18:28:07.436649+00:00 end:2025-02-04 18:38:08.264383+00:00 duration:600.827734
[2025-02-04T18:38:08.266+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): fetch_book_data> dag:<DAG: fetch_and_store_amazon_books> dagrun:<DagRun fetch_and_store_amazon_books @ 2024-06-23 00:00:00+00:00: scheduled__2024-06-23T00:00:00+00:00, state:running, queued_at: 2025-02-04 18:27:09.413063+00:00. externally triggered: False>
[2025-02-04T18:38:08.267+0000] {logging_mixin.py:190} INFO - Failure caused by {'DAG Id': 'fetch_and_store_amazon_books', 'Task Id': 'fetch_book_data', 'Run Id': 'scheduled__2024-06-23T00:00:00+00:00', 'Hostname': '01f8178c85f9', 'External Executor Id': 'f9861682-0bff-41e8-80af-ed6b910c53a2'}
[2025-02-04T18:38:08.268+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:38:08.268+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=fetch_and_store_amazon_books, task_id=fetch_book_data, run_id=scheduled__2024-06-23T00:00:00+00:00, execution_date=20240623T000000, start_date=20250204T182807, end_date=20250204T183808
[2025-02-04T18:38:08.271+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:38:08.271+0000] {processor.py:876} INFO - Executed callback for <TaskInstance: fetch_and_store_amazon_books.fetch_book_data scheduled__2024-06-23T00:00:00+00:00 [up_for_retry]> in state up_for_retry
[2025-02-04T18:38:08.273+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:38:08.273+0000] {taskinstance.py:3313} ERROR - {'DAG Id': 'fetch_and_store_amazon_books', 'Task Id': 'fetch_book_data', 'Run Id': 'scheduled__2024-06-24T00:00:00+00:00', 'Hostname': '01f8178c85f9', 'External Executor Id': 'bc25b82f-0159-4de4-9294-3e4fd763a682'}
[2025-02-04T18:38:08.277+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-02-04T18:38:08.278+0000] {logging_mixin.py:190} INFO - Task start:2025-02-04 18:27:52.991577+00:00 end:2025-02-04 18:38:08.277339+00:00 duration:615.285762
[2025-02-04T18:38:08.279+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): fetch_book_data> dag:<DAG: fetch_and_store_amazon_books> dagrun:<DagRun fetch_and_store_amazon_books @ 2024-06-24 00:00:00+00:00: scheduled__2024-06-24T00:00:00+00:00, state:running, queued_at: 2025-02-04 18:27:09.537956+00:00. externally triggered: False>
[2025-02-04T18:38:08.280+0000] {logging_mixin.py:190} INFO - Failure caused by {'DAG Id': 'fetch_and_store_amazon_books', 'Task Id': 'fetch_book_data', 'Run Id': 'scheduled__2024-06-24T00:00:00+00:00', 'Hostname': '01f8178c85f9', 'External Executor Id': 'bc25b82f-0159-4de4-9294-3e4fd763a682'}
[2025-02-04T18:38:08.281+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:38:08.281+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=fetch_and_store_amazon_books, task_id=fetch_book_data, run_id=scheduled__2024-06-24T00:00:00+00:00, execution_date=20240624T000000, start_date=20250204T182752, end_date=20250204T183808
[2025-02-04T18:38:08.286+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:38:08.285+0000] {processor.py:876} INFO - Executed callback for <TaskInstance: fetch_and_store_amazon_books.fetch_book_data scheduled__2024-06-24T00:00:00+00:00 [up_for_retry]> in state up_for_retry
[2025-02-04T18:38:08.288+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:38:08.288+0000] {taskinstance.py:3313} ERROR - {'DAG Id': 'fetch_and_store_amazon_books', 'Task Id': 'fetch_book_data', 'Run Id': 'scheduled__2024-06-29T00:00:00+00:00', 'Hostname': '01f8178c85f9', 'External Executor Id': '7253ef3b-42d1-4d7d-a464-24ab1e8d49a5'}
[2025-02-04T18:38:08.292+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-02-04T18:38:08.293+0000] {logging_mixin.py:190} INFO - Task start:2025-02-04 18:28:07.132560+00:00 end:2025-02-04 18:38:08.292109+00:00 duration:601.159549
[2025-02-04T18:38:08.294+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): fetch_book_data> dag:<DAG: fetch_and_store_amazon_books> dagrun:<DagRun fetch_and_store_amazon_books @ 2024-06-29 00:00:00+00:00: scheduled__2024-06-29T00:00:00+00:00, state:running, queued_at: 2025-02-04 18:27:10.179529+00:00. externally triggered: False>
[2025-02-04T18:38:08.294+0000] {logging_mixin.py:190} INFO - Failure caused by {'DAG Id': 'fetch_and_store_amazon_books', 'Task Id': 'fetch_book_data', 'Run Id': 'scheduled__2024-06-29T00:00:00+00:00', 'Hostname': '01f8178c85f9', 'External Executor Id': '7253ef3b-42d1-4d7d-a464-24ab1e8d49a5'}
[2025-02-04T18:38:08.295+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:38:08.295+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=fetch_and_store_amazon_books, task_id=fetch_book_data, run_id=scheduled__2024-06-29T00:00:00+00:00, execution_date=20240629T000000, start_date=20250204T182807, end_date=20250204T183808
[2025-02-04T18:38:08.299+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:38:08.299+0000] {processor.py:876} INFO - Executed callback for <TaskInstance: fetch_and_store_amazon_books.fetch_book_data scheduled__2024-06-29T00:00:00+00:00 [up_for_retry]> in state up_for_retry
[2025-02-04T18:38:08.301+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:38:08.301+0000] {taskinstance.py:3313} ERROR - {'DAG Id': 'fetch_and_store_amazon_books', 'Task Id': 'fetch_book_data', 'Run Id': 'scheduled__2024-06-30T00:00:00+00:00', 'Hostname': '01f8178c85f9', 'External Executor Id': '6e5d5c2b-6915-495f-b911-35ce2530d11b'}
[2025-02-04T18:38:08.305+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-02-04T18:38:08.306+0000] {logging_mixin.py:190} INFO - Task start:2025-02-04 18:28:05.144329+00:00 end:2025-02-04 18:38:08.305466+00:00 duration:603.161137
[2025-02-04T18:38:08.307+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): fetch_book_data> dag:<DAG: fetch_and_store_amazon_books> dagrun:<DagRun fetch_and_store_amazon_books @ 2024-06-30 00:00:00+00:00: scheduled__2024-06-30T00:00:00+00:00, state:running, queued_at: 2025-02-04 18:27:10.344083+00:00. externally triggered: False>
[2025-02-04T18:38:08.309+0000] {logging_mixin.py:190} INFO - Failure caused by {'DAG Id': 'fetch_and_store_amazon_books', 'Task Id': 'fetch_book_data', 'Run Id': 'scheduled__2024-06-30T00:00:00+00:00', 'Hostname': '01f8178c85f9', 'External Executor Id': '6e5d5c2b-6915-495f-b911-35ce2530d11b'}
[2025-02-04T18:38:08.309+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:38:08.309+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=fetch_and_store_amazon_books, task_id=fetch_book_data, run_id=scheduled__2024-06-30T00:00:00+00:00, execution_date=20240630T000000, start_date=20250204T182805, end_date=20250204T183808
[2025-02-04T18:38:08.313+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:38:08.313+0000] {processor.py:876} INFO - Executed callback for <TaskInstance: fetch_and_store_amazon_books.fetch_book_data scheduled__2024-06-30T00:00:00+00:00 [up_for_retry]> in state up_for_retry
[2025-02-04T18:38:08.316+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:38:08.316+0000] {taskinstance.py:3313} ERROR - {'DAG Id': 'fetch_and_store_amazon_books', 'Task Id': 'fetch_book_data', 'Run Id': 'manual__2025-02-04T18:27:07.412959+00:00', 'Hostname': '01f8178c85f9', 'External Executor Id': '52d5d1a4-a034-414c-b7f4-fc7329512f8f'}
[2025-02-04T18:38:08.322+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-02-04T18:38:08.323+0000] {logging_mixin.py:190} INFO - Task start:2025-02-04 18:28:13.564147+00:00 end:2025-02-04 18:38:08.318859+00:00 duration:594.754712
[2025-02-04T18:38:08.324+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): fetch_book_data> dag:<DAG: fetch_and_store_amazon_books> dagrun:<DagRun fetch_and_store_amazon_books @ 2025-02-04 18:27:07.412959+00:00: manual__2025-02-04T18:27:07.412959+00:00, state:running, queued_at: 2025-02-04 18:27:07.449238+00:00. externally triggered: True>
[2025-02-04T18:38:08.325+0000] {logging_mixin.py:190} INFO - Failure caused by {'DAG Id': 'fetch_and_store_amazon_books', 'Task Id': 'fetch_book_data', 'Run Id': 'manual__2025-02-04T18:27:07.412959+00:00', 'Hostname': '01f8178c85f9', 'External Executor Id': '52d5d1a4-a034-414c-b7f4-fc7329512f8f'}
[2025-02-04T18:38:08.326+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:38:08.326+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=fetch_and_store_amazon_books, task_id=fetch_book_data, run_id=manual__2025-02-04T18:27:07.412959+00:00, execution_date=20250204T182707, start_date=20250204T182813, end_date=20250204T183808
[2025-02-04T18:38:08.329+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:38:08.329+0000] {processor.py:876} INFO - Executed callback for <TaskInstance: fetch_and_store_amazon_books.fetch_book_data manual__2025-02-04T18:27:07.412959+00:00 [up_for_retry]> in state up_for_retry
[2025-02-04T18:38:08.343+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:38:08.342+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-04T18:38:08.370+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.365 seconds
[2025-02-04T18:38:38.672+0000] {processor.py:186} INFO - Started process (PID=551) to work on /opt/airflow/dags/app.py
[2025-02-04T18:38:38.674+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-04T18:38:38.678+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:38:38.678+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-04T18:38:38.754+0000] {processor.py:925} INFO - DAG(s) 'fetch_and_store_amazon_books' retrieved from /opt/airflow/dags/app.py
[2025-02-04T18:38:38.778+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:38:38.778+0000] {taskinstance.py:3313} ERROR - {'DAG Id': 'fetch_and_store_amazon_books', 'Task Id': 'fetch_book_data', 'Run Id': 'scheduled__2024-06-26T00:00:00+00:00', 'Hostname': '01f8178c85f9', 'External Executor Id': '308a60b7-289a-4df0-9031-bf5c882f5550'}
[2025-02-04T18:38:38.793+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-02-04T18:38:38.795+0000] {logging_mixin.py:190} INFO - Task start:2025-02-04 18:28:07.081438+00:00 end:2025-02-04 18:38:38.784909+00:00 duration:631.703471
[2025-02-04T18:38:38.797+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): fetch_book_data> dag:<DAG: fetch_and_store_amazon_books> dagrun:<DagRun fetch_and_store_amazon_books @ 2024-06-26 00:00:00+00:00: scheduled__2024-06-26T00:00:00+00:00, state:running, queued_at: 2025-02-04 18:27:09.773934+00:00. externally triggered: False>
[2025-02-04T18:38:38.798+0000] {logging_mixin.py:190} INFO - Failure caused by {'DAG Id': 'fetch_and_store_amazon_books', 'Task Id': 'fetch_book_data', 'Run Id': 'scheduled__2024-06-26T00:00:00+00:00', 'Hostname': '01f8178c85f9', 'External Executor Id': '308a60b7-289a-4df0-9031-bf5c882f5550'}
[2025-02-04T18:38:38.800+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:38:38.800+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=fetch_and_store_amazon_books, task_id=fetch_book_data, run_id=scheduled__2024-06-26T00:00:00+00:00, execution_date=20240626T000000, start_date=20250204T182807, end_date=20250204T183838
[2025-02-04T18:38:38.811+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:38:38.811+0000] {processor.py:876} INFO - Executed callback for <TaskInstance: fetch_and_store_amazon_books.fetch_book_data scheduled__2024-06-26T00:00:00+00:00 [up_for_retry]> in state up_for_retry
[2025-02-04T18:38:38.815+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:38:38.815+0000] {taskinstance.py:3313} ERROR - {'DAG Id': 'fetch_and_store_amazon_books', 'Task Id': 'fetch_book_data', 'Run Id': 'scheduled__2024-06-23T00:00:00+00:00', 'Hostname': '01f8178c85f9', 'External Executor Id': 'f9861682-0bff-41e8-80af-ed6b910c53a2'}
[2025-02-04T18:38:38.820+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-02-04T18:38:38.822+0000] {logging_mixin.py:190} INFO - Task start:2025-02-04 18:28:07.436649+00:00 end:2025-02-04 18:38:38.818404+00:00 duration:631.381755
[2025-02-04T18:38:38.823+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): fetch_book_data> dag:<DAG: fetch_and_store_amazon_books> dagrun:<DagRun fetch_and_store_amazon_books @ 2024-06-23 00:00:00+00:00: scheduled__2024-06-23T00:00:00+00:00, state:running, queued_at: 2025-02-04 18:27:09.413063+00:00. externally triggered: False>
[2025-02-04T18:38:38.824+0000] {logging_mixin.py:190} INFO - Failure caused by {'DAG Id': 'fetch_and_store_amazon_books', 'Task Id': 'fetch_book_data', 'Run Id': 'scheduled__2024-06-23T00:00:00+00:00', 'Hostname': '01f8178c85f9', 'External Executor Id': 'f9861682-0bff-41e8-80af-ed6b910c53a2'}
[2025-02-04T18:38:38.825+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:38:38.825+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=fetch_and_store_amazon_books, task_id=fetch_book_data, run_id=scheduled__2024-06-23T00:00:00+00:00, execution_date=20240623T000000, start_date=20250204T182807, end_date=20250204T183838
[2025-02-04T18:38:38.828+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:38:38.828+0000] {processor.py:876} INFO - Executed callback for <TaskInstance: fetch_and_store_amazon_books.fetch_book_data scheduled__2024-06-23T00:00:00+00:00 [up_for_retry]> in state up_for_retry
[2025-02-04T18:38:38.831+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:38:38.831+0000] {taskinstance.py:3313} ERROR - {'DAG Id': 'fetch_and_store_amazon_books', 'Task Id': 'fetch_book_data', 'Run Id': 'scheduled__2024-06-24T00:00:00+00:00', 'Hostname': '01f8178c85f9', 'External Executor Id': 'bc25b82f-0159-4de4-9294-3e4fd763a682'}
[2025-02-04T18:38:38.836+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-02-04T18:38:38.837+0000] {logging_mixin.py:190} INFO - Task start:2025-02-04 18:27:52.991577+00:00 end:2025-02-04 18:38:38.834208+00:00 duration:645.842631
[2025-02-04T18:38:38.838+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): fetch_book_data> dag:<DAG: fetch_and_store_amazon_books> dagrun:<DagRun fetch_and_store_amazon_books @ 2024-06-24 00:00:00+00:00: scheduled__2024-06-24T00:00:00+00:00, state:running, queued_at: 2025-02-04 18:27:09.537956+00:00. externally triggered: False>
[2025-02-04T18:38:38.839+0000] {logging_mixin.py:190} INFO - Failure caused by {'DAG Id': 'fetch_and_store_amazon_books', 'Task Id': 'fetch_book_data', 'Run Id': 'scheduled__2024-06-24T00:00:00+00:00', 'Hostname': '01f8178c85f9', 'External Executor Id': 'bc25b82f-0159-4de4-9294-3e4fd763a682'}
[2025-02-04T18:38:38.840+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:38:38.840+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=fetch_and_store_amazon_books, task_id=fetch_book_data, run_id=scheduled__2024-06-24T00:00:00+00:00, execution_date=20240624T000000, start_date=20250204T182752, end_date=20250204T183838
[2025-02-04T18:38:38.845+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:38:38.844+0000] {processor.py:876} INFO - Executed callback for <TaskInstance: fetch_and_store_amazon_books.fetch_book_data scheduled__2024-06-24T00:00:00+00:00 [up_for_retry]> in state up_for_retry
[2025-02-04T18:38:38.849+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:38:38.849+0000] {taskinstance.py:3313} ERROR - {'DAG Id': 'fetch_and_store_amazon_books', 'Task Id': 'fetch_book_data', 'Run Id': 'scheduled__2024-06-29T00:00:00+00:00', 'Hostname': '01f8178c85f9', 'External Executor Id': '7253ef3b-42d1-4d7d-a464-24ab1e8d49a5'}
[2025-02-04T18:38:38.854+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-02-04T18:38:38.855+0000] {logging_mixin.py:190} INFO - Task start:2025-02-04 18:28:07.132560+00:00 end:2025-02-04 18:38:38.852055+00:00 duration:631.719495
[2025-02-04T18:38:38.856+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): fetch_book_data> dag:<DAG: fetch_and_store_amazon_books> dagrun:<DagRun fetch_and_store_amazon_books @ 2024-06-29 00:00:00+00:00: scheduled__2024-06-29T00:00:00+00:00, state:running, queued_at: 2025-02-04 18:27:10.179529+00:00. externally triggered: False>
[2025-02-04T18:38:38.857+0000] {logging_mixin.py:190} INFO - Failure caused by {'DAG Id': 'fetch_and_store_amazon_books', 'Task Id': 'fetch_book_data', 'Run Id': 'scheduled__2024-06-29T00:00:00+00:00', 'Hostname': '01f8178c85f9', 'External Executor Id': '7253ef3b-42d1-4d7d-a464-24ab1e8d49a5'}
[2025-02-04T18:38:38.858+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:38:38.858+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=fetch_and_store_amazon_books, task_id=fetch_book_data, run_id=scheduled__2024-06-29T00:00:00+00:00, execution_date=20240629T000000, start_date=20250204T182807, end_date=20250204T183838
[2025-02-04T18:38:38.863+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:38:38.863+0000] {processor.py:876} INFO - Executed callback for <TaskInstance: fetch_and_store_amazon_books.fetch_book_data scheduled__2024-06-29T00:00:00+00:00 [up_for_retry]> in state up_for_retry
[2025-02-04T18:38:38.866+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:38:38.865+0000] {taskinstance.py:3313} ERROR - {'DAG Id': 'fetch_and_store_amazon_books', 'Task Id': 'fetch_book_data', 'Run Id': 'scheduled__2024-06-30T00:00:00+00:00', 'Hostname': '01f8178c85f9', 'External Executor Id': '6e5d5c2b-6915-495f-b911-35ce2530d11b'}
[2025-02-04T18:38:38.870+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-02-04T18:38:38.871+0000] {logging_mixin.py:190} INFO - Task start:2025-02-04 18:28:05.144329+00:00 end:2025-02-04 18:38:38.868470+00:00 duration:633.724141
[2025-02-04T18:38:38.872+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): fetch_book_data> dag:<DAG: fetch_and_store_amazon_books> dagrun:<DagRun fetch_and_store_amazon_books @ 2024-06-30 00:00:00+00:00: scheduled__2024-06-30T00:00:00+00:00, state:running, queued_at: 2025-02-04 18:27:10.344083+00:00. externally triggered: False>
[2025-02-04T18:38:38.873+0000] {logging_mixin.py:190} INFO - Failure caused by {'DAG Id': 'fetch_and_store_amazon_books', 'Task Id': 'fetch_book_data', 'Run Id': 'scheduled__2024-06-30T00:00:00+00:00', 'Hostname': '01f8178c85f9', 'External Executor Id': '6e5d5c2b-6915-495f-b911-35ce2530d11b'}
[2025-02-04T18:38:38.874+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:38:38.874+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=fetch_and_store_amazon_books, task_id=fetch_book_data, run_id=scheduled__2024-06-30T00:00:00+00:00, execution_date=20240630T000000, start_date=20250204T182805, end_date=20250204T183838
[2025-02-04T18:38:38.878+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:38:38.877+0000] {processor.py:876} INFO - Executed callback for <TaskInstance: fetch_and_store_amazon_books.fetch_book_data scheduled__2024-06-30T00:00:00+00:00 [up_for_retry]> in state up_for_retry
[2025-02-04T18:38:38.880+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:38:38.880+0000] {taskinstance.py:3313} ERROR - {'DAG Id': 'fetch_and_store_amazon_books', 'Task Id': 'fetch_book_data', 'Run Id': 'scheduled__2024-07-02T00:00:00+00:00', 'Hostname': '01f8178c85f9', 'External Executor Id': '901839be-5bb8-4950-b6ba-0a058ed7bd8d'}
[2025-02-04T18:38:38.884+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-02-04T18:38:38.885+0000] {logging_mixin.py:190} INFO - Task start:2025-02-04 18:28:05.029206+00:00 end:2025-02-04 18:38:38.882118+00:00 duration:633.852912
[2025-02-04T18:38:38.886+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): fetch_book_data> dag:<DAG: fetch_and_store_amazon_books> dagrun:<DagRun fetch_and_store_amazon_books @ 2024-07-02 00:00:00+00:00: scheduled__2024-07-02T00:00:00+00:00, state:running, queued_at: 2025-02-04 18:27:10.735300+00:00. externally triggered: False>
[2025-02-04T18:38:38.887+0000] {logging_mixin.py:190} INFO - Failure caused by {'DAG Id': 'fetch_and_store_amazon_books', 'Task Id': 'fetch_book_data', 'Run Id': 'scheduled__2024-07-02T00:00:00+00:00', 'Hostname': '01f8178c85f9', 'External Executor Id': '901839be-5bb8-4950-b6ba-0a058ed7bd8d'}
[2025-02-04T18:38:38.889+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:38:38.888+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=fetch_and_store_amazon_books, task_id=fetch_book_data, run_id=scheduled__2024-07-02T00:00:00+00:00, execution_date=20240702T000000, start_date=20250204T182805, end_date=20250204T183838
[2025-02-04T18:38:38.892+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:38:38.892+0000] {processor.py:876} INFO - Executed callback for <TaskInstance: fetch_and_store_amazon_books.fetch_book_data scheduled__2024-07-02T00:00:00+00:00 [up_for_retry]> in state up_for_retry
[2025-02-04T18:38:38.894+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:38:38.894+0000] {taskinstance.py:3313} ERROR - {'DAG Id': 'fetch_and_store_amazon_books', 'Task Id': 'fetch_book_data', 'Run Id': 'scheduled__2024-07-04T00:00:00+00:00', 'Hostname': '01f8178c85f9', 'External Executor Id': 'bbc9bccc-8601-4dad-a03b-272c57e92bee'}
[2025-02-04T18:38:38.899+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-02-04T18:38:38.900+0000] {logging_mixin.py:190} INFO - Task start:2025-02-04 18:28:17.306445+00:00 end:2025-02-04 18:38:38.896955+00:00 duration:621.59051
[2025-02-04T18:38:38.901+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): fetch_book_data> dag:<DAG: fetch_and_store_amazon_books> dagrun:<DagRun fetch_and_store_amazon_books @ 2024-07-04 00:00:00+00:00: scheduled__2024-07-04T00:00:00+00:00, state:running, queued_at: 2025-02-04 18:27:11.191934+00:00. externally triggered: False>
[2025-02-04T18:38:38.902+0000] {logging_mixin.py:190} INFO - Failure caused by {'DAG Id': 'fetch_and_store_amazon_books', 'Task Id': 'fetch_book_data', 'Run Id': 'scheduled__2024-07-04T00:00:00+00:00', 'Hostname': '01f8178c85f9', 'External Executor Id': 'bbc9bccc-8601-4dad-a03b-272c57e92bee'}
[2025-02-04T18:38:38.903+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:38:38.903+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=fetch_and_store_amazon_books, task_id=fetch_book_data, run_id=scheduled__2024-07-04T00:00:00+00:00, execution_date=20240704T000000, start_date=20250204T182817, end_date=20250204T183838
[2025-02-04T18:38:38.906+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:38:38.906+0000] {processor.py:876} INFO - Executed callback for <TaskInstance: fetch_and_store_amazon_books.fetch_book_data scheduled__2024-07-04T00:00:00+00:00 [up_for_retry]> in state up_for_retry
[2025-02-04T18:38:38.908+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:38:38.908+0000] {taskinstance.py:3313} ERROR - {'DAG Id': 'fetch_and_store_amazon_books', 'Task Id': 'fetch_book_data', 'Run Id': 'scheduled__2024-06-21T00:00:00+00:00', 'Hostname': '01f8178c85f9', 'External Executor Id': '722fea71-8334-43c8-a84a-af1324084809'}
[2025-02-04T18:38:38.913+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-02-04T18:38:38.913+0000] {logging_mixin.py:190} INFO - Task start:2025-02-04 18:27:59.981237+00:00 end:2025-02-04 18:38:38.910845+00:00 duration:638.929608
[2025-02-04T18:38:38.914+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): fetch_book_data> dag:<DAG: fetch_and_store_amazon_books> dagrun:<DagRun fetch_and_store_amazon_books @ 2024-06-21 00:00:00+00:00: scheduled__2024-06-21T00:00:00+00:00, state:running, queued_at: 2025-02-04 18:27:09.109872+00:00. externally triggered: False>
[2025-02-04T18:38:38.916+0000] {logging_mixin.py:190} INFO - Failure caused by {'DAG Id': 'fetch_and_store_amazon_books', 'Task Id': 'fetch_book_data', 'Run Id': 'scheduled__2024-06-21T00:00:00+00:00', 'Hostname': '01f8178c85f9', 'External Executor Id': '722fea71-8334-43c8-a84a-af1324084809'}
[2025-02-04T18:38:38.917+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:38:38.917+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=fetch_and_store_amazon_books, task_id=fetch_book_data, run_id=scheduled__2024-06-21T00:00:00+00:00, execution_date=20240621T000000, start_date=20250204T182759, end_date=20250204T183838
[2025-02-04T18:38:38.921+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:38:38.920+0000] {processor.py:876} INFO - Executed callback for <TaskInstance: fetch_and_store_amazon_books.fetch_book_data scheduled__2024-06-21T00:00:00+00:00 [up_for_retry]> in state up_for_retry
[2025-02-04T18:38:38.931+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:38:38.931+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-04T18:38:38.960+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.297 seconds
[2025-02-04T18:39:09.335+0000] {processor.py:186} INFO - Started process (PID=615) to work on /opt/airflow/dags/app.py
[2025-02-04T18:39:09.340+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-04T18:39:09.350+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:39:09.349+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-04T18:39:09.485+0000] {processor.py:925} INFO - DAG(s) 'fetch_and_store_amazon_books' retrieved from /opt/airflow/dags/app.py
[2025-02-04T18:39:09.511+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:39:09.511+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-04T18:39:09.545+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.224 seconds
[2025-02-04T18:39:39.762+0000] {processor.py:186} INFO - Started process (PID=679) to work on /opt/airflow/dags/app.py
[2025-02-04T18:39:39.767+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-04T18:39:39.773+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:39:39.773+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-04T18:39:39.873+0000] {processor.py:925} INFO - DAG(s) 'fetch_and_store_amazon_books' retrieved from /opt/airflow/dags/app.py
[2025-02-04T18:39:39.899+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:39:39.898+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-04T18:39:39.932+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.186 seconds
[2025-02-04T18:40:10.133+0000] {processor.py:186} INFO - Started process (PID=743) to work on /opt/airflow/dags/app.py
[2025-02-04T18:40:10.136+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-04T18:40:10.140+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:40:10.140+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-04T18:40:10.209+0000] {processor.py:925} INFO - DAG(s) 'fetch_and_store_amazon_books' retrieved from /opt/airflow/dags/app.py
[2025-02-04T18:40:10.231+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:40:10.231+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-04T18:40:10.262+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.137 seconds
[2025-02-04T18:40:40.462+0000] {processor.py:186} INFO - Started process (PID=807) to work on /opt/airflow/dags/app.py
[2025-02-04T18:40:40.471+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-04T18:40:40.497+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:40:40.495+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-04T18:40:40.716+0000] {processor.py:925} INFO - DAG(s) 'fetch_and_store_amazon_books' retrieved from /opt/airflow/dags/app.py
[2025-02-04T18:40:40.844+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:40:40.840+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-04T18:40:41.125+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.717 seconds
[2025-02-04T18:41:11.327+0000] {processor.py:186} INFO - Started process (PID=871) to work on /opt/airflow/dags/app.py
[2025-02-04T18:41:11.329+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-04T18:41:11.333+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:41:11.332+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-04T18:41:11.399+0000] {processor.py:925} INFO - DAG(s) 'fetch_and_store_amazon_books' retrieved from /opt/airflow/dags/app.py
[2025-02-04T18:41:11.432+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:41:11.425+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-04T18:41:11.473+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.151 seconds
[2025-02-04T18:41:41.944+0000] {processor.py:186} INFO - Started process (PID=935) to work on /opt/airflow/dags/app.py
[2025-02-04T18:41:41.946+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-04T18:41:41.949+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:41:41.949+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-04T18:41:42.009+0000] {processor.py:925} INFO - DAG(s) 'fetch_and_store_amazon_books' retrieved from /opt/airflow/dags/app.py
[2025-02-04T18:41:42.034+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:41:42.033+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-04T18:41:42.070+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.131 seconds
[2025-02-04T18:41:59.709+0000] {processor.py:186} INFO - Started process (PID=943) to work on /opt/airflow/dags/app.py
[2025-02-04T18:41:59.713+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-04T18:41:59.723+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:41:59.721+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-04T18:41:59.977+0000] {processor.py:925} INFO - DAG(s) 'fetch_and_store_amazon_books' retrieved from /opt/airflow/dags/app.py
[2025-02-04T18:42:00.043+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:42:00.043+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-04T18:42:00.105+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.414 seconds
[2025-02-04T18:42:30.497+0000] {processor.py:186} INFO - Started process (PID=1013) to work on /opt/airflow/dags/app.py
[2025-02-04T18:42:30.500+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-04T18:42:30.507+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:42:30.505+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-04T18:42:30.633+0000] {processor.py:925} INFO - DAG(s) 'fetch_and_store_amazon_books' retrieved from /opt/airflow/dags/app.py
[2025-02-04T18:42:30.664+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:42:30.664+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-04T18:42:30.710+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.221 seconds
[2025-02-04T18:43:01.463+0000] {processor.py:186} INFO - Started process (PID=1081) to work on /opt/airflow/dags/app.py
[2025-02-04T18:43:01.468+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-04T18:43:01.495+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:43:01.492+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-04T18:43:01.649+0000] {processor.py:925} INFO - DAG(s) 'fetch_and_store_amazon_books' retrieved from /opt/airflow/dags/app.py
[2025-02-04T18:43:01.717+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:43:01.715+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-04T18:43:01.777+0000] {logging_mixin.py:190} INFO - [2025-02-04T18:43:01.771+0000] {dag.py:4180} INFO - Setting next_dagrun for fetch_and_store_amazon_books to 2025-02-02 00:00:00+00:00, run_after=2025-02-03 00:00:00+00:00
[2025-02-04T18:43:01.822+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.374 seconds
